<?php

namespace AppBundle\Repository;

/**
 * CamposAfinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamposAfinesRepository extends \Doctrine\ORM\EntityRepository
{
}
