<?php

namespace AppBundle\Repository;

/**
 * EstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatusRepository extends \Doctrine\ORM\EntityRepository
{
}
