<?php

namespace AppBundle\Repository;

/**
 * SolicitudNotasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudNotasRepository extends \Doctrine\ORM\EntityRepository
{
}
