<?php

namespace AppBundle\Repository;

/**
 * SolicitudEstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudEstatusRepository extends \Doctrine\ORM\EntityRepository
{
}
