<?php

namespace AppBundle\Repository;

/**
 * UsuarioCamposAfineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCamposAfineRepository extends \Doctrine\ORM\EntityRepository
{
}
